config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies
  resources :shows
  resources :theaters
  resources :users
  resources :reservations

  root "movies#index"

  post 'shows/:id/reserve' => 'shows#reserve'

  scope '/api' do
  	scope '/v1' do
  		get '/movies', to: 'movies#api_index'
  		get '/movies/:id', to: 'movies#api_show'
      get '/movies/:id/actors', to: 'movies#api_index_movie_actors'
  		get '/shows', to: 'shows#api_index'
  		get '/shows/:id', to: 'shows#api_show'
      get '/theaters', to: 'theaters#api_index'
  		get '/theaters/:id', to: 'theaters#api_show'
  		get '/seats/:theater_id', to: 'theaters#api_index_seats'
  		get '/reservations/:show_id', to: 'reservations#api_index_reserved_seats'
      get '/reservations/for_user/:email/:password', to: 'reservations#api_index_user_reservations'
      get '/reservations/:id/seats', to: 'reservations#api_index_reservation_seats'
      get '/shows/:id/reserve/:seats/:email/:password', to: 'shows#api_reserve_seats'
  	end
  end
  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	before_action :find_movie, only: [:show, :edit, :update, :destroy]

  def index
    time_range = DateTime.now.beginning_of_day()..DateTime.now.end_of_day() + 365.day
  	@movies = Movie.includes(:shows).order('shows.datetime ASC')#.where("shows.datetime > ?  OR shows = ?", DateTime.now, nil)
  end

  def new
  	@movie = Movie.new
  end

  def create
  	@movie = Movie.new(movie_params)
    if @movie.poster_url != nil && @movie.poster_url != ""
      @movie.poster_from_url @movie.poster_url
    end
    @movie.trailer_url = sanitize_trailer_url(@movie.trailer_url)
  	if @movie.save
  		redirect_to @movie
  	else
  		render 'new'
  	end
  end

  def show
  end

  def edit
    authenticate_user!
  end

  def update
		if @movie.update(movie_params)
      if @movie.poster_url != nil && @movie.poster_url != ""
        @movie.poster_from_url @movie.poster_url
      end
      @movie.trailer_url = sanitize_trailer_url(@movie.trailer_url)
      @movie.save
			redirect_to @movie
		else
			render 'edit'
		end
  end

  def destroy
  	@movie.destroy
  	redirect_to movies_path
  end

  def api_index
    time_range = DateTime.now.beginning_of_day()..DateTime.now.end_of_day()
    @movies = Movie.includes(:shows).where('shows.datetime' => time_range).order('shows.datetime ASC')
    render json: @movies, status: :ok
  end

  def api_show
    @movie = Movie.find(params[:id])
    render json: @movie, status: :ok
  end

  def api_index_movie_actors
    @movie = Movie.find(params[:id])
    @actors = Actor.includes(:movies).where(movie_id: @movie.id)
    render json: @actors, status: :ok
  end

  private

  def find_movie
  	@movie = Movie.find(params[:id])
  end

  def sanitize_trailer_url(url)
    url.remove!("https://www.youtube.com/watch?v=")
    url.remove!("http://www.youtube.com/watch?v=")
    url.remove!("www.youtube.com/watch?v=")
    url.remove!("youtube.com/watch?v=")
  end

  def movie_params
  	params.require(:movie).permit(:title, :poster, :poster_url, :plot, :duration, :director, :genere, :trailer_url, actors_attributes: [:id, :name, :_destroy], shows_attributes: [:id, :datetime, :theater_id, :price, :_destroy])
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_actor_fields.html.erb
<div class="nested-fields">
	<%= link_to_remove_association "X", f , id: "deleteActor" %>
	<%= f.input :name, placeholder: 'Leonardo DiCaprio' , id: "actorName" %>
</div>

app/views/movies/_form.html.erb
<%= simple_form_for @movie, html: {multipart: true} do |f| %>
	<div class="nav_bar">
		<div class="sub_nav left">
			<%= link_to "Cinema Paradiso", root_path, class: "title" %>
			<%= link_to "Programmazione", movies_path, class: "nav_item" %>
			<% if user_signed_in? %>
				<% if current_user.admin %>
					<%= link_to "Prenotazioni", reservations_path, class: "nav_item" %>
					<%= link_to "Spettacoli", shows_path, class: "nav_item" %>
				<% elsif current_user.reservations.count > 0 %>
					<%= link_to "Le mie prenotazioni", reservations_path, class: "nav_item" %>
				<% end %>
			<% end %>
		</div>
		<div class="sub_nav right">
			<% if user_signed_in? %>
				<%= link_to "Elimina", @movie, method: :delete, class: "nav_item", data: { confirm: 'Sei sicuro?' } %>
				<%= link_to "Annulla", root_path, class: "nav_item" %>
				<%= f.button :submit, value: "Salva", class: "nav_item" %>
				<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav_item" %>
			<% else %>
				<%= link_to "Sign Up", new_user_registration_path, class: "nav_item" %>
				<%= link_to "Sign In", new_user_session_path, class: "nav_item" %>
			<% end %>
		</div>
	</div>
	
	<% flash.each do |key, value| %>
	    <div class="notification <%= key %>"><%= value %></div>
	<% end %>

	<div class="movies_form">
		<% if user_signed_in? && current_user.admin %>
			<img class="poster" id="poster" src="<%= @movie.poster.url(:large) %>"/>
			<div class="info">
				<div class="poster">
					<label>Poster</label>
					<%= f.file_field :poster, id: "posterUpload" %>
					<%= f.input :poster_url, placeholder: 'oppure scrivi URL qui' %>
				</div>
				<script>
					function handleFileSelect(evt) {
    				var files = evt.target.files; // FileList object
    				// Loop through the FileList and render image files as thumbnails.
    				for (var i = 0, f; f = files[i]; i++) {
    	  			// Only process image files.
    	  			if (!f.type.match('image.*')) {
    	  			  continue;
    	  			}
    	  			var reader = new FileReader();
    	  			// Closure to capture the file information.
    	  			reader.onload = (function(theFile) {
    	  		  	return function(e) {
    	  	  	  	// Update image.
    	  	  	  	document.getElementById("poster").src=e.target.result;
    	  	  		};
    	  			})(f);
    	  			// Read in the image file as a data URL.
    	  			reader.readAsDataURL(f);
    				}	
  				}
  				document.getElementById('posterUpload').addEventListener('change', handleFileSelect, false);
				</script>
				<div class="title"><%= f.input :title, placeholder: 'Titanic', label: 'Titolo' %></div>
				<div class="autocomplete hidden">
					<div class="found_title">Intendi <span id="found_title"></span>?</div>
					<div class="autocomplete_button">Completa automaticamente</div>
				</div>
				<script>
					var baseurl;
    				var request = new XMLHttpRequest();
					request.open('GET', 'https://api.themoviedb.org/3/configuration?api_key=663428f9bca787c67552f9c76c0362b9');
					request.setRequestHeader('Accept', 'application/json');
					request.onreadystatechange = function () {
  						if (this.readyState === 4) {
   							var response = this.responseText;
   							var obj = JSON.parse(response);
   							baseurl = obj.images.base_url;
  						}
					};
					request.send();

					var suggestAutocompletion = true;

					$('form').on('keyup change', 'input#movie_title', function(){
						if (suggestAutocompletion) {
							var inputTitle = $('input#movie_title').val();
    						if (inputTitle.length >= 3) {
    							findMovie(inputTitle, "it");
    						} else {
    							resetFormPreview();
    							$(".autocomplete").addClass("hidden");
    						}
						}
					});

					var id, title, plot, duration, genere, director, actors, trailer_url, poster_url;

					function findMovie(t, language) {
						t = escape(t);
    					var request = new XMLHttpRequest();
						request.open('GET', 'https://api.themoviedb.org/3/search/movie?api_key=663428f9bca787c67552f9c76c0362b9&query=' + t + '&language=' + language);
						request.setRequestHeader('Accept', 'application/json');
						request.onreadystatechange = function () {
  							if (this.readyState === 4) {
   								var response = this.responseText;
   								var obj = JSON.parse(response);
   								obj = obj.results[0];  // Best result.
   								if (obj != null) {
   									$(".autocomplete").removeClass("hidden");
   									// Get title.
   									title = obj.title;
   									$("#found_title").text(title);
   									// Get id.
   									var newId = obj.id;
   									if (id != newId) {
   										// Update movie info.
   										getMovieInfo(newId, language);
   									}
   								}
  							}
						};
						request.send();
					}

					function getMovieInfo(id, language) {
						var request = new XMLHttpRequest();
						request.open('GET', 'https://api.themoviedb.org/3/movie/' + id + '?api_key=663428f9bca787c67552f9c76c0362b9&language=' + language);
						request.setRequestHeader('Accept', 'application/json');
						request.onreadystatechange = function () {
  							if (this.readyState === 4) {
   								var response = this.responseText;
   								var obj = JSON.parse(response);
   								// Get plot.
   								plot = obj.overview;
   								// Get duration.
   								duration = obj.runtime;
   								// Get genere.
   								var genres = obj.genres;
   								genere = "";
								for (var i = 0; i < genres.length; i++) {
   									if (genere == "") {
   										genere = genres[i].name;
   									} else {
   										genere = genere + ", " + genres[i].name;
   									}
   								}
   								// Get poster URL.
   								poster_url = null;
   								poster_url = obj.poster_path;
   								// Get actors and director (and trailer URL).
   								getMovieActorsAndDirector(id);
  							}
						};
						request.send();
					}

					function getMovieActorsAndDirector(id) {
						var request = new XMLHttpRequest();
						request.open('GET', 'https://api.themoviedb.org/3/movie/' + id + '/credits?api_key=663428f9bca787c67552f9c76c0362b9');
						request.setRequestHeader('Accept', 'application/json');
						request.onreadystatechange = function () {
							if (this.readyState === 4) {
   								var response = this.responseText;
   								var obj = JSON.parse(response);
   								// Get actors.
   								var cast = obj.cast;
   								actors = [];
   								var numberOfActorsToGet = 5
   								for (var i = 0; i < cast.length; i++) {
   									if (numberOfActorsToGet > 0) {
   										actors.push(cast[i].name);
   										numberOfActorsToGet--;
   									}
   								}
   								// Get director.
   								var crew = obj.crew;
   								for (var i = 0; i < crew.length; i++) {
   									if (crew[i].department == "Directing") {
   										director = crew[i].name;
   										numberOfActorsToGet--;
   									}
   								}
   								// Get trailer URL.
   								getMovieTrailerURL(id);
  							}
  							
						};
						request.send();
					}

					function getMovieTrailerURL(id) {
						var request = new XMLHttpRequest();
						request.open('GET', 'https://api.themoviedb.org/3/movie/' + id + '/videos?api_key=663428f9bca787c67552f9c76c0362b9');
						request.setRequestHeader('Accept', 'application/json');
						request.onreadystatechange = function () {
  							if (this.readyState === 4) {
   								var response = this.responseText;
   								var obj = JSON.parse(response);
   								// Get trailer url.
   								if (obj.results.length > 0) {
   									trailer_url = obj.results[0].key;
   								}
   								
   								// Update preview.
   								updateFormPreview();
  							}
						};
						request.send();
					}

					function updateFormPreview() {
						if (plot != null) {
							$('textarea#movie_plot').attr("placeholder", plot);
						}
						if (duration != null) {
							$('input#movie_duration').attr("placeholder", duration);
						}
						if (genere != null) {
							$('input#movie_genere').attr("placeholder", genere);
						}
						if (director != null) {
							$('input#movie_director').attr("placeholder", director);
						}
						if (poster_url != null) {
							$('input#movie_poster_url').attr("placeholder", baseurl + "/original/" + poster_url);
						}
						if (trailer_url != null) {
							$('input#movie_trailer_url').attr("placeholder", trailer_url);
						}
						// Attori
						//for (var i = 0; i < actors.length; i++) {
						//	document.getElementById("addActor").click();
						//}
					}

					function resetFormPreview() {
						if (plot != null) {
							$('textarea#movie_plot').attr("placeholder", "");
							$('input#movie_duration').attr("placeholder", "");
							$('input#movie_genere').attr("placeholder", "");
							$('input#movie_director').attr("placeholder", "");
							$('input#movie_poster_url').attr("placeholder", "");
							$('input#movie_trailer_url').attr("placeholder", "");
						}
						// Attori
					}

					function updateForm() {
						suggestAutocompletion = false;
						$(".autocomplete").addClass("hidden");
						if (title != null) {
							$('input#movie_title').val(title);
						}
						if (plot != null) {
							$('textarea#movie_plot').val(plot);
						}
						if (duration != null) {
							$('input#movie_duration').val(duration);
						}
						if (genere != null) {
							$('input#movie_genere').val(genere);
						}
						if (director != null) {
							$('input#movie_director').val(director);
						}
						if (poster_url != null) {
							$('input#movie_poster_url').val(baseurl + "/original/" + poster_url);
							updatePosterFromURL();
						}
						if (trailer_url != null) {
							$('input#movie_trailer_url').val(trailer_url);
						}
						// Attori
						suggestAutocompletion = true;
					}

					$('.autocomplete').click(function () {
        				updateForm();
    				});

    				$('input#movie_poster_url').change(function() {
     					updatePosterFromURL();
    				});

    				function updatePosterFromURL() {
    					$("img.poster").attr("src", $('input#movie_poster_url').val());
    				}
				</script>
				<div class="plot"><%= f.input :plot, placeholder: "Rose ha diciassette anni, una madre egoista, un fidanzato facoltoso e una vita pianificata. Imbarcata sul Titanic e insoddisfatta della propria subalternità al futuro sposo incontra Jack, romantico disegnatore della terza classe che ha vinto a poker un biglietto per l'America. Contro le convenzioni e il destino, che chiederà il conto in una notte senza luna, Rose e Jack si innamorano, spiegando il loro spirito come i motori del più grande transatlantico del mondo. Lanciato nella sua prima traversata oceanica il Titanic è colpito al cuore da un iceberg, 'affondando' millecinquecento persone e il futuro dei due giovani amanti. Ottantaquattro anni dopo l'ultracentenaria Rose, scampata al naufragio e sopravvissuta a Jack, racconterà a un gruppo di scienziati la meraviglia di un amore interclassista e la stupidità di un mondo diviso in classi. Un mondo che il Titanic inabisserà in un oceano nero il 15 aprile del 1912.", label: 'Trama' %></div>
				<div class="genere_duration_director_actors">
					<div class="duration"><%= f.input :duration, placeholder: '123', label: 'Durata' %></div>
					<div class="director"><%= f.input :director, placeholder: 'James Cameron', label: 'Regista' %></div>
					<div class="genere"><%= f.input :genere, placeholder: 'Drammatico', label: 'Genere' %></div>
					<div class="actor_form">
						<label>Attori</label>
						<%= link_to_add_association "+ Aggiungi attore", f, :actors, "data-association-insertion-method": "append", id: "addActor" %> 
						<%= f.simple_fields_for :actors do |actor| %>
							<%= render 'actor_fields', f: actor %>
						<% end %>
					</div>
				</div>
				<div class="trailer_url"><%= f.input :trailer_url, placeholder: '(URL YouTube)' %></div>
				<div class="shows">
					<div class="show_form">
						<label>Spettacoli</label>
						<%= link_to_add_association "+ Aggiungi spettacolo", f, :shows, "data-association-insertion-method": "append" %> 
						<%= f.simple_fields_for :shows do |show| %>
							<% if show.object.datetime > DateTime.now %>
								<%= render 'show_fields', f: show %>
							<% end %>
						<% end %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
<% end %>

app/views/movies/_show_fields.html.erb
<div class="nested-fields">
	<%= link_to_remove_association "X", f %>
	<div class="form">
		<%= f.input :datetime, minute_step: 5 %> — 
		<%= f.association :theater %> — 
		<%= f.input :price, collection: [3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0], selected: f.object.price, prompt: "Prezzo", selected: f.object.price %><span class="currency"> €</span>
	</div>
</div>

app/views/movies/edit.html.erb
<%= render 'form' %>

app/views/movies/index.html.erb
<div class="nav_bar">
	<div class="sub_nav left">
		<%= link_to "Cinema Paradiso", root_path, class: "title" %>
		<%= link_to "Programmazione", movies_path, class: "nav_item selected" %>
		<% if user_signed_in? %>
			<% if current_user.admin %>
				<%= link_to "Prenotazioni", reservations_path, class: "nav_item" %>
				<%= link_to "Spettacoli", shows_path, class: "nav_item" %>
			<% elsif current_user.reservations.count > 0 %>
				<%= link_to "Le mie prenotazioni", reservations_path, class: "nav_item" %>
			<% end %>
		<% end %>
	</div>
	<div class="sub_nav right">
		<% if user_signed_in? %>
			<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav_item" %>
		<% else %>
			<%= link_to "Sign Up", new_user_registration_path, class: "nav_item" %>
			<%= link_to "Sign In", new_user_session_path, class: "nav_item" %>
		<% end %>
	</div>
</div>

<% flash.each do |key, value| %>
    <div class="notification <%= key %>"><%= value %></div>
<% end %>

<div class="movies_index">
	<div class="movies">
		<% movies = 0 %>
		<% if current_user && current_user.admin %>
			<div class="movie" id="newMovie">
				<% movies = movies + 1 %>
				<a href="<%= new_movie_path %>">
					<div class="poster_container">
						<img class="poster cover", src="/images/missing_standard.jpg"/>
						<div class="plus">+</div>
						<div class="add_movie">Aggiungi film</div>
					</div>
				</a>
			</div>
		<% end %>
		<% @movies.each do |movie| %>
			<% unless (current_user && current_user.admin) || !movie.shows.where(datetime: (DateTime.now.beginning_of_day()..(DateTime.now + (6 * 24).hours).end_of_day())).empty? %>
				<% next %>
			<% end %>
			<div class="movie">
				<% movies = movies + 1 %>
				<a href="<%= movie_path(movie) %>">
					<div class="poster_container ">
						<img class="poster cover", src="<%= movie.poster.url(:standard) %>"/>
						<div class="poster_info">
							<div class="plot"><%= truncate(movie.plot, :length => 200) %></div>
							<div class="genere_duration_director">
								<div class="genere"><%= movie.genere %></div>&nbsp;/&nbsp;
								<div class="duration"><%= movie.duration %> min.</div>&nbsp;/&nbsp;
								<div class="director">Regia <%= movie.director %></div>
							</div>
						</div>
					</div>
				</a>
				<div class="info">
					<div class="title"><a href="<%= movie_path(movie) %>"><%= movie.title %></a></div>
					<div class="shows">
						<% i = 0 %>
						<% while i < 7 do %>
							<div class="day">
								<% unless movie.shows.where(datetime: (DateTime.now + (i * 24).hours).beginning_of_day()..(DateTime.now + (i * 24).hours).end_of_day()).empty? %>
									<% date = (DateTime.now + (i * 24).hours).strftime("%a %d:") %>
									<% if date == DateTime.now.strftime("%a %d:") %>
										<% date = "Oggi:" %>
									<% elsif date == (DateTime.now + 24.hours).strftime("%a %d:") %>
										<% date = "Domani:" %>
									<% end %>
									<% date.sub! 'Monday', 'Lunedì' %>
									<% date.sub! 'Tuesday', 'Martedì' %>
									<% date.sub! 'Wednesday', 'Mercoledì' %>
									<% date.sub! 'Thursday', 'Giovedì' %>
									<% date.sub! 'Friday', 'Venerdì' %>
									<% date.sub! 'Saturday', 'Sabato' %>
									<% date.sub! 'Sunday', 'Domenica' %>
									<% date.sub! 'Mon', 'Lun' %>
									<% date.sub! 'Tue', 'Mar' %>
									<% date.sub! 'Wed', 'Mer' %>
									<% date.sub! 'Thu', 'Gio' %>
									<% date.sub! 'Fri', 'Ven' %>
									<% date.sub! 'Sat', 'Sab' %>
									<% date.sub! 'Sun', 'Dom' %>
									<div class="date"><%= date %>&nbsp;</div>
									<div class="times">
										<% movie.shows.where(datetime: (DateTime.now + (i * 24).hours).beginning_of_day()..(DateTime.now + (i * 24).hours).end_of_day()).order(:datetime).each do |show| %>
											<a href="<%= show_path(show) %>"><div class="time <% if show.datetime < DateTime.now %>past<% end %>"><%= show.datetime.strftime("%H:%M") %></div></a>
										<% end %>
									</div>
								<% end %>
							</div>
							<% i = i + 1 %>
						<% end %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
	<% if movies > 5 %>
		<div class="scroll_left">
				<div class="arrow_container">
					<img class="arrow_left", src="/images/arrow_left.png"/>
				</div>
		</div>
		<div class="scroll_right">
				<div class="arrow_container">
					<img class="arrow_right", src="/images/arrow_right.png"/>
				</div>
		</div>
	<% end %>
</div>
<script>
	$(".arrow_right").click(function() {
		var movieWidth = $(".movie").width();
		var scrollLeft = $('.movies').scrollLeft();
		var extra = 0;
		if (scrollLeft % movieWidth != 0) {
			extra = (movieWidth - scrollLeft % movieWidth);
		}
	  $('.movies').animate({scrollLeft: scrollLeft + extra + movieWidth}, 700);
	});

	$(".arrow_left").click(function() {
		var movieWidth = $(".movie").width();
		var scrollLeft = $('.movies').scrollLeft();
	  $('.movies').animate({scrollLeft: scrollLeft - scrollLeft % movieWidth - movieWidth}, 700);
	});

	jQuery(function($) {
    $('.movies').on('scroll', function() {
        if($(this).scrollLeft() == 0) {
           $(".arrow_left").hide();
        } else {
        	$(".arrow_left").show();
        }
        if($(".movie:last").position().left + $(".movie").width() == $(".movies").width()) {
          $(".arrow_right").hide();
        } else {
        	$(".arrow_right").show();
        }
    })
});
</script>

app/views/movies/new.html.erb
<%= render 'form' %>

app/views/movies/show.html.erb
<div class="nav_bar">
	<div class="sub_nav left">
		<%= link_to "Cinema Paradiso", root_path, class: "title" %>
		<%= link_to "Programmazione", movies_path, class: "nav_item" %>
		<% if user_signed_in? %>
			<% if current_user.admin %>
				<%= link_to "Prenotazioni", reservations_path, class: "nav_item" %>
				<%= link_to "Spettacoli", shows_path, class: "nav_item" %>
			<% elsif current_user.reservations.count > 0 %>
				<%= link_to "Le mie prenotazioni", reservations_path, class: "nav_item" %>
			<% end %>
		<% end %>
	</div>
	<div class="sub_nav right">
		<% if user_signed_in? %>
			<% if current_user.admin %>
				<%= link_to "Modifica", edit_movie_path(@movie), class: "nav_item" %>
			<% end %>
			<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav_item" %>
		<% else %>
			<%= link_to "Sign Up", new_user_registration_path, class: "nav_item" %>
			<%= link_to "Sign In", new_user_session_path, class: "nav_item" %>
		<% end %>
	</div>
</div>

<% flash.each do |key, value| %>
    <div class="notification <%= key %>"><%= value %></div>
<% end %>

<div class="movies_show">
	<img class="poster", src="<%= @movie.poster.url(:large) %>"/>
	<div class="info">
		<div class="title"><%= @movie.title %></div>
		<div class="plot"><%= @movie.plot %></div>
		<div class="genere_duration_director_actors">
			<div class="genere"><%= @movie.genere %></div>&nbsp;&nbsp;/&nbsp;&nbsp;
			<div class="duration"><%= @movie.duration %> minuti</div>&nbsp;&nbsp;/&nbsp;&nbsp;
			<div class="director">Regia <%= @movie.director %></div>
			<div class="actors">
				<% unless @movie.actors.empty? %>
					&nbsp;&nbsp;/&nbsp;Con&nbsp;
					<% comma = false %>
					<% @movie.actors.each do |actor| %>
						<% if comma %>
							,&nbsp;
						<% end %>
						<div class="actor"><%= actor.name %></div>
						<% comma = true %>
					<% end %>
				<% end %>
				.
			</div>
		</div>
		<% if @movie.trailer_url && @movie.trailer_url != "" %>
			<div class="trailer_container">
				<iframe class="trailer" frameborder="0" height="100%" width="100%" src="https://www.youtube.com/embed/<%= @movie.trailer_url %>?rel=0&amp;showinfo=0" allowfullscreen></iframe>
			</div>
		<% end %>
		<div class="shows">
			<% i = 0 %>
			<% while i < 7 do %>
				<div class="day">
					<% unless @movie.shows.where(datetime: (DateTime.now + (i * 24).hours).beginning_of_day()..(DateTime.now + (i * 24).hours).end_of_day()).empty? %>
						<% date = (DateTime.now + (i * 24).hours).strftime("%a %d:") %>
						<% if date == DateTime.now.strftime("%a %d:") %>
							<% date = "Oggi:" %>
						<% elsif date == (DateTime.now + 24.hours).strftime("%a %d:") %>
							<% date = "Domani:" %>
						<% end %>
						<% date.sub! 'Monday', 'Lunedì' %>
						<% date.sub! 'Tuesday', 'Martedì' %>
						<% date.sub! 'Wednesday', 'Mercoledì' %>
						<% date.sub! 'Thursday', 'Giovedì' %>
						<% date.sub! 'Friday', 'Venerdì' %>
						<% date.sub! 'Saturday', 'Sabato' %>
						<% date.sub! 'Sunday', 'Domenica' %>
						<% date.sub! 'Mon', 'Lun' %>
						<% date.sub! 'Tue', 'Mar' %>
						<% date.sub! 'Wed', 'Mer' %>
						<% date.sub! 'Thu', 'Gio' %>
						<% date.sub! 'Fri', 'Ven' %>
						<% date.sub! 'Sat', 'Sab' %>
						<% date.sub! 'Sun', 'Dom' %>
						<div class="date"><%= date %>&nbsp;</div>
						<div class="times">
							<% @movie.shows.where(datetime: (DateTime.now + (i * 24).hours).beginning_of_day()..(DateTime.now + (i * 24).hours).end_of_day()).order(:datetime).each do |show| %>
								<a href="<%= show_path(show) %>"><div class="time <% if show.datetime < DateTime.now %>past<% end %>"><%= show.datetime.strftime("%H:%M") %></div></a>
							<% end %>
						</div>
					<% end %>
				</div>
				<% i = i + 1 %>
			<% end %>
		</div>
	</div>
</div>