config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies
  resources :shows
  resources :theaters
  resources :users
  resources :reservations

  root "movies#index"

  post 'shows/:id/reserve' => 'shows#reserve'

  scope '/api' do
  	scope '/v1' do
  		get '/movies', to: 'movies#api_index'
  		get '/movies/:id', to: 'movies#api_show'
      get '/movies/:id/actors', to: 'movies#api_index_movie_actors'
  		get '/shows', to: 'shows#api_index'
  		get '/shows/:id', to: 'shows#api_show'
      get '/theaters', to: 'theaters#api_index'
  		get '/theaters/:id', to: 'theaters#api_show'
  		get '/seats/:theater_id', to: 'theaters#api_index_seats'
  		get '/reservations/:show_id', to: 'reservations#api_index_reserved_seats'
      get '/reservations/for_user/:email/:password', to: 'reservations#api_index_user_reservations'
      get '/reservations/:id/seats', to: 'reservations#api_index_reservation_seats'
      get '/shows/:id/reserve/:seats/:email/:password', to: 'shows#api_reserve_seats'
  	end
  end
  

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :show
	has_and_belongs_to_many :seats
	belongs_to :user
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def new
  	@reservation = Reservation.new
  end

  def create
  	@reservation = Reservation.new(reservation_params)
    @reservation.user_id = current_user.id
  	if @reservation.save
  		redirect_to @reservation
  	else
  		render 'new'
  	end
  end

  def index
    authenticate_user!
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
  end

  def get_seats
    @string = params[:string] || session[:string] 
    respond_to do |format|
      if @string  
       redirect_to @reservation
      else 
       render 'new'
      end
    end
  end

  def api_index_reserved_seats
    @show = Show.find(params[:show_id])
    @seats = Seat.includes(:reservations).where('reservations.show_id' => @show.id)
    render json: @seats, status: :ok
  end

  def api_index_user_reservations
    @user = User.find_by_email(params[:email])
    if @user && @user.valid_password?(params[:password])
      @reservation = Reservation.where(user: @user)
      render json: @reservation, status: :ok
    else
      render json: "Email o password non corrette", status: :unauthorized
    end
  end

  def api_index_reservation_seats
    @reservation = Reservation.find(params[:id])
    @seats = Seat.includes(:reservations).where('reservations.id' => @reservation.id)
    render json: @seats, status: :ok
  end

  private

  def reservation_params
  	params.require(:reservation).permit(:user, :show, :seats)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= simple_form_for @reservation do |f| %>
	<%= f.association :show %>
	<%= f.association :seats %>
	<%= f.button :submit %>
<% end %>

app/views/reservations/index.html.erb
<div class="nav_bar">
	<div class="sub_nav left">
		<%= link_to "Cinema Paradiso", root_path, class: "title" %>
		<%= link_to "Programmazione", movies_path, class: "nav_item" %>
		<% if user_signed_in? %>
			<% if current_user.admin %>
				<%= link_to "Prenotazioni", reservations_path, class: "nav_item selected" %>
				<%= link_to "Spettacoli", shows_path, class: "nav_item" %>
			<% elsif current_user.reservations.count > 0 %>
				<%= link_to "Le mie prenotazioni", reservations_path, class: "nav_item selected" %>
			<% end %>
		<% end %>
	</div>
	<div class="sub_nav right">
		<% if user_signed_in? %>
			<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav_item" %>
		<% else %>
			<%= link_to "Sign Up", new_user_registration_path, class: "nav_item" %>
			<%= link_to "Sign In", new_user_session_path, class: "nav_item" %>
		<% end %>
	</div>
</div>

<% flash.each do |key, value| %>
    <div class="notification <%= key %>"><%= value %></div>
<% end %>

<div class="reservations_index">
	<% @reservations.each do |reservation| %>
		<% if !current_user.admin && reservation.user != current_user %>
			<% next %>
		<% end %>
		<% if current_user.admin && reservation.user == current_user %>
			<% next %>
		<% end %>
		<% if reservation.show.datetime < DateTime.now %>
			<% next %>
		<% end %>
		<% if reservation.show.movie == nil %>
			<% next %>
		<% end %>
		<div class="reservation">
			<div class="info">
				<a href="/movies/<%= reservation.show.movie.id %>">
					<div class="title"><%= reservation.show.movie.title %></div>
				</a>
			</div>
			<div class="info">
				<a href="/reservations/<%= reservation.id %>">
					<% date =  reservation.show.datetime.strftime("%A %d") %>
					<% if date == DateTime.now.strftime("%A %d") %>
						<% date = "Oggi" %>
					<% elsif date == (DateTime.now + 24.hours).strftime("%A %d") %>
						<% date = "Domani" %>
					<% end %>
					<% date.sub! 'Monday', 'Lunedì' %>
					<% date.sub! 'Tuesday', 'Martedì' %>
					<% date.sub! 'Wednesday', 'Mercoledì' %>
					<% date.sub! 'Thursday', 'Giovedì' %>
					<% date.sub! 'Friday', 'Venerdì' %>
					<% date.sub! 'Saturday', 'Sabato' %>
					<% date.sub! 'Sunday', 'Domenica' %>
					<% date.sub! 'Mon', 'Lun' %>
					<% date.sub! 'Tue', 'Mar' %>
					<% date.sub! 'Wed', 'Mer' %>
					<% date.sub! 'Thu', 'Gio' %>
					<% date.sub! 'Fri', 'Ven' %>
					<% date.sub! 'Sat', 'Sab' %>
					<% date.sub! 'Sun', 'Dom' %>
					<div class="date"><%= date %></div>
					<div class="time"><%= reservation.show.datetime.strftime("%H:%M") %></div>
					<div class="theater"><%= reservation.show.theater.name %></div>
				</a>
			</div>
			<div class="info">
				<% if reservation.seats.count == 1 %>
					<span class="label">Posto</span>
				<% else %>
					<span class="label">Posti</span>
				<% end %>
				<% reservation.seats.each do |seat| %>
					<a href="/reservations/<%= reservation.id %>">
						<div class="seat">
							<div class="row"><%= seat.row %></div>
							<div class="number"><%= seat.number %></div>
						</div>
					</a>
				<% end %>
				<% if current_user.admin %>
					<div class="user"><%= reservation.user.email %></div>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/reservations/new.html.erb
<%= render 'form' %>

app/views/reservations/show.html.erb
<div class="nav_bar">
	<div class="sub_nav left">
		<%= link_to "Cinema Paradiso", root_path, class: "title" %>
		<%= link_to "Programmazione", movies_path, class: "nav_item" %>
		<% if user_signed_in? %>
			<% if current_user.admin %>
				<%= link_to "Prenotazioni", reservations_path, class: "nav_item" %>
				<%= link_to "Spettacoli", shows_path, class: "nav_item" %>
			<% elsif current_user.reservations.count > 0 %>
				<%= link_to "Le mie prenotazioni", reservations_path, class: "nav_item" %>
			<% end %>
		<% end %>
	</div>
	<div class="sub_nav right">
		<% if user_signed_in? %>
			<%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav_item" %>
		<% else %>
			<%= link_to "Sign Up", new_user_registration_path, class: "nav_item" %>
			<%= link_to "Sign In", new_user_session_path, class: "nav_item" %>
		<% end %>
	</div>
</div>

<% flash.each do |key, value| %>
    <div class="notification <%= key %>"><%= value %></div>
<% end %>

<div class="reservations_show">
	<img class="poster", src="<%= @reservation.show.movie.poster.url(:large) %>"/>
	<div class="info">
	<a href="<%= movie_path(@reservation.show.movie) %>">
		<div class="title"><%= @reservation.show.movie.title %></div>
	</a>
	<% date =  @reservation.show.datetime.strftime("%A %d") %>
	<% if date == DateTime.now.strftime("%A %d") %>
		<% date = "Oggi" %>
	<% elsif date == (DateTime.now + 24.hours).strftime("%A %d") %>
		<% date = "Domani" %>
	<% end %>
	<% date.sub! 'Monday', 'Lunedì' %>
	<% date.sub! 'Tuesday', 'Martedì' %>
	<% date.sub! 'Wednesday', 'Mercoledì' %>
	<% date.sub! 'Thursday', 'Giovedì' %>
	<% date.sub! 'Friday', 'Venerdì' %>
	<% date.sub! 'Saturday', 'Sabato' %>
	<% date.sub! 'Sunday', 'Domenica' %>
	<% date.sub! 'Mon', 'Lun' %>
	<% date.sub! 'Tue', 'Mar' %>
	<% date.sub! 'Wed', 'Mer' %>
	<% date.sub! 'Thu', 'Gio' %>
	<% date.sub! 'Fri', 'Ven' %>
	<% date.sub! 'Sat', 'Sab' %>
	<% date.sub! 'Sun', 'Dom' %>
	<div class="date"> - <%= date %></div>
	<div class="time"><%= @reservation.show.datetime.strftime("%H:%M") %></div>
	<div class="theater"><%= @reservation.show.theater.name %></div>
	<div class="seats">
		<div class="screen-container">
			<div class="screen"></div>
			<div>Schermo</div>
		</div>
		<% row = "" %>
		<% @reservation.show.theater.seats.each do |seat| %>
			<% if row != seat.row %>
				<% if row != "" %>
					</div>
				<% end %>
				<% row = seat.row %>
				<div class="<%= row %>">
					<div class="row">
						<%= row %>
					</div>
			<% end %>
			<div class="seat <%= row %><%= seat.number %><% @reservation.seats.each do |reservationSeat| %>
				<% if seat == reservationSeat %>
					 reserved
				<% end %>
			<% end %>" onclick="select('<%= row %>', <%= seat.number %>)"><%= seat.number %></div>
		<% end %>
				</div>
		<div class="legend">
			<div class="sample"><div class="seat reserved">X</div><% if @reservation.seats.count == 1 %>il tuo posto<% else %>i tuoi posti<% end %></div>
		</div>
	</div>
</div>