config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :movies
  resources :shows
  resources :theaters
  resources :users
  resources :reservations

  root "movies#index"

  post 'shows/:id/reserve' => 'shows#reserve'

  scope '/api' do
  	scope '/v1' do
  		get '/movies', to: 'movies#api_index'
  		get '/movies/:id', to: 'movies#api_show'
      get '/movies/:id/actors', to: 'movies#api_index_movie_actors'
  		get '/shows', to: 'shows#api_index'
  		get '/shows/:id', to: 'shows#api_show'
      get '/theaters', to: 'theaters#api_index'
  		get '/theaters/:id', to: 'theaters#api_show'
  		get '/seats/:theater_id', to: 'theaters#api_index_seats'
  		get '/reservations/:show_id', to: 'reservations#api_index_reserved_seats'
      get '/reservations/for_user/:email/:password', to: 'reservations#api_index_user_reservations'
      get '/reservations/:id/seats', to: 'reservations#api_index_reservation_seats'
      get '/shows/:id/reserve/:seats/:email/:password', to: 'shows#api_reserve_seats'
  	end
  end
  

end

app/models/theater.rb
class Theater < ActiveRecord::Base
	has_many :shows
	has_many :seats
end

app/controllers/theaters_controller.rb
class TheatersController < ApplicationController
	before_action :find_theater, only: [:show, :edit, :update, :destroy]

  def index
  	@theaters = Theater.all
  end

  def new
  	@theater = Theater.new
  end

  def create
  	@theater = Theater.new(theater_params)
  	if @theater.save
  		redirect_to @theater
  	else
  		render 'new'
  	end
  end

  def show
  end

  def api_index
    @theaters = Theater.all
    render json: @theaters, status: :ok
  end

  def api_show
    @theater = Theater.find(params[:id])
    render json: @theater, status: :ok
  end

  def api_index_seats
    @theater = Theater.find(params[:theater_id])
    @seats = Seat.where(theater: @theater)
    render json: @seats, status: :ok
  end

  def edit
  end

  def update
		if @theater.update(theater_params)
			redirect_to @theater
		else
			render 'edit'
		end
  end

  def destroy
  	@theater.destroy
  	redirect_to theaters_path
  end

  private

  def find_theater
  	@theater = Theater.find(params[:id])
  end

  def theater_params
  	params.require(:theater).permit(:name, :seats)
  end
end

app/helpers/theaters_helper.rb
module TheatersHelper
end

app/views/theaters/_form.html.erb
<%= form_for @theater do |f| %>
	<%= f.label :name %><br/>
	<%= f.text_field :name %><br/>
	<br/>
	<%= f.label :seats %><br/>
	<%= f.text_field :seats %><br/>
	<br/>
	<%= f.submit %>
<% end %>

app/views/theaters/edit.html.erb
<h1>Edit theater</h1>

<%= render 'form' %>

app/views/theaters/index.html.erb
<%= link_to "Aggiungi sala", new_theater_path %>
<% @theaters.each do |theater| %>
	<div>
		<h3><%= theater.name %></h3>
		<div><%= theater.seats %></div>
		<%= link_to "More info", theater %>
	</div>
<% end %>

app/views/theaters/new.html.erb
<h1>New theater</h1>

<%= render 'form' %>

app/views/theaters/show.html.erb
<%= link_to "Torna alla lista delle sale", theaters_path %>
<h3><%= @theater.name %></h3>
<div><%= @theater.seats %></div>
<div>
	<% @theater.shows.each do |show| %>
		<div><%= show.movie.title %></div>
		<div><%= show.datetime.to_formatted_s(:short) %></div>
	<% end %>
</div>
<%= link_to "Modifica", edit_theater_path(@theater) %>
<%= link_to "Elimina", theater_path(@theater), method: :delete, data: {confirm: "Questa azione non potrà essere annulata. Sei sicuro di voler eliminare la sala?"} %>